### ISSUE TITLE
avrusb.sch mistake in connection

### ISSUE THREAD

**Issue by sash13** [nekromant/hw-transformatic#1]
I builded nrf24l01-dongle but OS doesn't recognize it. I resoldered 1.5KOm resistor before 68 Ohm closely to Dm and it's working.

**Comment by nekromant** [comment]
1. You're likely posting this issue to the wrong repo
2. As for nrf24l01-dongle - mine work fine and the position of the pullup resistor should not affect it at all

**Comment by sash13** [comment]
But nrf24l01-dongle used shematics from bits/avrusb.sch and downloaded it from 

> git@invyl.ath.cx/~/kicad/bits

It's unvalible now. I had suggested it's from hw-transformatic, and downloaded this blueprint for kicad.

Original v-usb connection disign when resistor connected before 68Ohm work for me. If resistor soldered after 68Ohm resistor circuit doesn't work and reconnected in system continuosly.

**Comment by nekromant** [comment]
I see. Forgot to add the missing bit to nrf24l01-dongle repo, will fix tomorrow. 

Regarding the resistor - I've double-checked, both variants work for me. 1.5k +- 5% is the pullup for usb device detection. Unless you've mixed up things and using 680 instead of 68 Ohms, things should work. If adding 68 more Ohms to the pullup is enough to screw things up for you - something's really bad is going on there. I'd start with checking the power supply voltage and that you are NOT using long usb cables. vusb doesn't like those in general.
